# Generated by Django 4.2.7 on 2023-11-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='EmployeeGroup',
        ),
    ]
