# Generated by Django 4.2.7 on 2023-11-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_group_employeegroup'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='manager',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_manager_per_user'),
        ),
    ]
